# 1. Tensor Manipulation
    - numpy vs. torch

## 1-1 Tensor Manipulation1

In [1]:
import numpy as np
import torch

### 1D Array with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [3]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  1
Shape of t :  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with Numpy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [6]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


# Pytorch is like Numpy(but better)

### 1D Array with PyTorch
    1. dim = rank
    2. shape = size
    3. element, slicing 은 numpy와 동일

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [8]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [9]:
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D

In [12]:
t = torch.FloatTensor([[1., 2., 3.],
                                   [4., 5., 6.],
                                   [7., 8., 9.],
                                   [10., 11., 12.]
                                ])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [14]:
print(t.dim())  # rank
print(t.shape)
print(t.size()) # shape

2
torch.Size([4, 3])
torch.Size([4, 3])


In [15]:
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### 4D

In [16]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                                     [5, 6, 7, 8],
                                     [9, 10, 11, 12]],
                                    [[13, 14, 15, 16],
                                     [17, 18, 19, 20],
                                     [21, 22, 23, 24]]
                                    ]])

In [17]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


# Frequently Used Operations in PyTorch

### Mul vs. Matmul

In [19]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
# 행렬 곱셈
print(m1.matmul(m2)) # 2 x 1, m1 x m2

print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
# 행별 계산
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Broadcasting

In [20]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
m1 + m2

tensor([[5., 5.]])

In [21]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
m1 + m2

tensor([[4., 5.]])

In [22]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
# 1+3  1+4
# 2+3  2+4
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

### Mean

In [23]:
t = torch.FloatTensor([1, 2])
t.mean() # 전체평균

tensor(1.5000)

In [24]:
t = torch.LongTensor([1, 2]) # float만 계산 가능하다!!
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [25]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [26]:
print(t.mean()) # 전체
print(t.mean(dim=0)) # 첫번째 차원 단위의 평균 : 1,3의 평균 / 2,4
print(t.mean(dim=1)) # 두번째 차원 단위의 평균 : 1,2 / 3,4
print(t.mean(dim=-1)) # 마지막 차원 단위의 평균 -> 1

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### sum

In [27]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [28]:
t.max()

tensor(4.)

In [29]:
t.max(dim=0) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [30]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [31]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## 1-2 Tensor Manipulation2

### view
    - reshape

In [34]:
t = np.array([[[0, 1, 2],
                     [3, 4, 5]],

                    [[6, 7, 8],
                     [9, 10, 11]]])
ft = torch.FloatTensor(t)
ft.shape

torch.Size([2, 2, 3])

In [37]:
ft.view([-1]).shape # element

torch.Size([12])

In [38]:
print(ft.view([-1, 3]))
ft.view([-1, 3]).shape

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


torch.Size([4, 3])

In [39]:
print(ft.view([-1, 1, 3]))
ft.view([-1, 1, 3]).shape

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


torch.Size([4, 1, 3])

### Squeeze
    - 원소가 1인 차원을 없애준다
    ex. 3x1 -> 3

In [40]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
ft.shape

tensor([[0.],
        [1.],
        [2.]])


torch.Size([3, 1])

In [41]:
print(ft.squeeze())
ft.squeeze().shape

tensor([0., 1., 2.])


torch.Size([3])

### unsqueeze
     - 인수로 받은 위치에 새로운 차원을 삽입한다.
     ex. 0번째에 1 삽입
     3 -> 1x3

In [42]:
ft = torch.Tensor([0, 1, 2])
ft.shape

torch.Size([3])

In [43]:
print(ft.unsqueeze(0))
ft.unsqueeze(0).shape

tensor([[0., 1., 2.]])


torch.Size([1, 3])

In [46]:
print(ft.view(1, -1))
ft.view(1, -1).shape

tensor([[0., 1., 2.]])


torch.Size([1, 3])

In [47]:
print(ft.unsqueeze(1))
ft.unsqueeze(1).shape

tensor([[0.],
        [1.],
        [2.]])


torch.Size([3, 1])

In [48]:
print(ft.unsqueeze(-1))
ft.unsqueeze(-1).shape

tensor([[0.],
        [1.],
        [2.]])


torch.Size([3, 1])

### scatter_ : for one-hot encoding

In [10]:
lt = torch.LongTensor([[0], [1], [2], [0]])
lt

tensor([[0],
        [1],
        [2],
        [0]])

In [12]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 2)
one_hot

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.],
        [2., 0., 0.]])

### casting

In [52]:
lt = torch.LongTensor([1, 2, 3, 4])
lt

tensor([1, 2, 3, 4])

In [53]:
lt.float()

tensor([1., 2., 3., 4.])

In [54]:
bt = torch.ByteTensor([True, False, False, True])
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [55]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### concatenation

In [56]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [57]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### stacking

In [58]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [59]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [60]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

### ones amd zeros like

In [61]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [62]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place operation

In [63]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [64]:
print(x.mul(2.))
x

tensor([[2., 4.],
        [6., 8.]])


tensor([[1., 2.],
        [3., 4.]])

In [65]:
print(x.mul_(2.))
x

tensor([[2., 4.],
        [6., 8.]])


tensor([[2., 4.],
        [6., 8.]])

### zip

In [66]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [67]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
